### ISSUE TITLE
hello friend; just noting key spelling errors.

### ISSUE THREAD

**Issue by megalithic** [Oliver-Leete/Configs#1]
https://github.com/Oliver-Leete/Configs/blob/b9dfb0d63077108426ffa40e8cead00c49e657a8/nvim/lua/compleation_config.lua#L128

**Comment by Oliver-Leete** [comment]
Oh wow, thanks for that. That explains the sluggish typing in big buffers.

**Comment by megalithic** [comment]
my pleasure!
